### ISSUE TITLE
Dead-lock on Windows when subref to enter dies 

### ISSUE THREAD

**Issue by jjatria** [marioroy/mutex-perl#1]
When the code reference passed to `enter` dies under Windows, the lock is created but never released, which can create a dead lock.

The below one-liner will work on Linux:

``` perl
$ perl -MMutex -E '
    my $lock = Mutex->new;
    eval { $lock->enter( sub { say "a"; die } ) };
           $lock->enter( sub { say "b"      } )
'
```

but it will hang on Windows.

A patch like the one below seems to fix the issue with what seem to be minimal changes (although it raises the minimum supported version of Perl from 5.8 to 5.14):

```diff
diff --git a/lib/Mutex/Channel.pm b/lib/Mutex/Channel.pm
index 7901b5a..1d15c0f 100644
--- a/lib/Mutex/Channel.pm
+++ b/lib/Mutex/Channel.pm
@@ -20,6 +20,7 @@ use base 'Mutex';
+use Feature::Compat::Defer;
 use Mutex::Util;
 use Scalar::Util 'looks_like_number';
 use Time::HiRes 'alarm';
 
 my $is_MSWin32 = ($^O eq 'MSWin32') ? 1 : 0;
 my $use_pipe = ($^O !~ /mswin|mingw|msys|cygwin/i && $] gt '5.010000');
@@ -98,12 +99,14 @@ sub synchronize {
     Mutex::Util::_sysread($obj->{_r_sock}, $b, 1), $obj->{ $pid } = 1
         unless $obj->{ $pid };
 
+    defer {
+        CORE::syswrite($obj->{_w_sock}, '0'), $obj->{ $pid } = 0;
+    }
+
     (defined wantarray)
         ? @ret = wantarray ? $code->(@_) : scalar $code->(@_)
         : $code->(@_);
 
-    CORE::syswrite($obj->{_w_sock}, '0'), $obj->{ $pid } = 0;
-
     return wantarray ? @ret : $ret[-1];
 }
```

Alternatively, this also works, but is a more invasive change:

``` diff
diff --git a/lib/Mutex/Channel.pm b/lib/Mutex/Channel.pm                                                                                
index 7901b5a..4680106 100644                                                                                                           
--- a/lib/Mutex/Channel.pm                                                                                                              
+++ b/lib/Mutex/Channel.pm                                                                                                              
@@ -20,6 +20,7 @@ use base 'Mutex';                                                                                                     
 use Mutex::Util;
 use Scalar::Util 'looks_like_number';
 use Time::HiRes 'alarm';
+use Try::Tiny;
 
 my $is_MSWin32 = ($^O eq 'MSWin32') ? 1 : 0;
 my $use_pipe = ($^O !~ /mswin|mingw|msys|cygwin/i && $] gt '5.010000');
@@ -98,11 +99,17 @@ sub synchronize {
     Mutex::Util::_sysread($obj->{_r_sock}, $b, 1), $obj->{ $pid } = 1
         unless $obj->{ $pid };
 
-    (defined wantarray)
-        ? @ret = wantarray ? $code->(@_) : scalar $code->(@_)
-        : $code->(@_);
-
-    CORE::syswrite($obj->{_w_sock}, '0'), $obj->{ $pid } = 0;
+    try {
+        (defined wantarray)
+            ? @ret = wantarray ? $code->(@_) : scalar $code->(@_)
+            : $code->(@_);
+    }
+    catch {
+        die $_;
+    }
+    finally {
+        CORE::syswrite($obj->{_w_sock}, '0'), $obj->{ $pid } = 0;
+    };
 
     return wantarray ? @ret : $ret[-1];
 }
```

I would be happy to submit a PR in this direction if this is something you'd be interested in.

**Comment by marioroy** [comment]
Thank you @jjatria. I will take a look tomorrow. The defer feature is awesome. The try/catch/finally is a working solution, but want to measure the overhead. I will try a guard also. Supporting old Perl is no longer fun.

**Comment by marioroy** [comment]
I compared Feature::Compat::Defer (uses native defer feature or Syntax::Keyword::Defer), guard, and try block.

```text
for (1..100000) {
    $lock->enter( sub { ; } );
}

Mutex 1.009             0.125s
native defer feature    0.128s 
Syntax::Keyword::Defer  0.134s
guard                   0.176s
try/catch/finally       0.641s
```

Needless to say, I cannot use Try::Tiny due to the added overhead. The Syntax::Keyword::Defer seems like the path forward, but lack confidence seeing Syntax::Keyword::Defer failures on the Windows platform. Also, old Perl is not supported.

http://matrix.cpantesters.org/?dist=Syntax-Keyword-Defer+0.09

After review, the guard path was chosen and not worry about breaking old code. There's another issue. I will fix the lock re-entrant capability on the Windows platform.

**Comment by jjatria** [comment]
This looks good to me, and the guard seems like the safer way forward if old Perl support is still a must.

Thanks for taking a look at this!

I imagine a similar change will be needed in MCE::Mutex?

**Comment by marioroy** [comment]
About old Perl, I have no choice for MCE unfortunately. But unsure about Mutex. The changes were committed to the repository. I wish to update MCE before publishing to Meta::CPAN. In case I spot something else.

Thank you for reaching out.

**Comment by marioroy** [comment]
I applied a correction. Mutex 1.010 is final.

**Comment by jjatria** [comment]
Thanks for the quick turn around!

**Comment by marioroy** [comment]
Mutex 1.011 and MCE 1.889 were released and published to Meta::CPAN. I bumped the version for Mutex in the event folks had installed 1.010 from GitHub before the final edits were made.

**Comment by jjatria** [comment]
Thank you!
